### ISSUE TITLE
关于部分组件可视化无法完整解析的问题

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs-App-Store#1]
以这个package为例：
![image](https://user-images.githubusercontent.com/21079031/97824480-03bab680-1cf7-11eb-9431-70dfce74ee4c.png)
当完成创建之后，
![image](https://user-images.githubusercontent.com/21079031/97824496-10d7a580-1cf7-11eb-8663-316d745825c8.png)
我只修改一个地域：
![image](https://user-images.githubusercontent.com/21079031/97824508-19c87700-1cf7-11eb-90dc-2a2380b92805.png)
他整个右边的yaml就发生了变化。

原因分析：Triggers的字结构有很多，目前没办法正确匹对到一致的结构，导致的问题出现。这里会让用户体验非常不好。

**Comment by hanxie-crypto** [comment]
这个问题修复了吧

**Comment by anycodes** [comment]
我刚才看貌似还是这样子。

**Comment by hanxie-crypto** [comment]
问题修复，升级客户端 到0.0.25 版本以上即可
