### ISSUE TITLE
组件过多导致上层内容展开失败

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs-App-Store#13]
测试案例：
![image](https://user-images.githubusercontent.com/21079031/98619660-ad74f580-233e-11eb-9471-c097d56d4764.png)

在这个里面，标签未显示完整，最好修复一下，没显示完整的可以用`...`表示

![image](https://user-images.githubusercontent.com/21079031/98619686-b8c82100-233e-11eb-9ba8-7d61eceac97b.png)

创建之后，上面显示不完整

点击最后一个会出现问题：
![image](https://user-images.githubusercontent.com/21079031/98619729-d09fa500-233e-11eb-889d-581fc04c1f74.png)

**Comment by hanxie-crypto** [comment]
增加多内容可折叠的交互
