### ISSUE TITLE
查看详情页面可能会布局错乱

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs-App-Store#3]
应用：`s-aws-lambda-api-dome`
现象：由于hompage过长，导致布局错乱
![image](https://user-images.githubusercontent.com/21079031/97866621-38eef500-1d47-11eb-836d-dd9d871e72f6.png)
不确定这个布局是不是在预期范围内，优先级不高，可以延期修正

**Comment by weitanai** [comment]
已经修复了
